### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by neuhaus** [heavykick/MilkVRLauncher#1]
Thanks for writing this useful tool!
Could you please whip up a minimal README that explains how to build this thing?
After building,  I need to sign the binary with my osig file from Oculus, right?

**Comment by heavykick** [comment]
Hi :)
no, this is a simple app made with VisualStudio. It is not a VR app and does not do anything with oculus mobile api ...
But the last compiled version is available as release in github.
I want to transfer this to AndroidStudio soon bacause I would like to support more intent-filter

-------- Ursprüngliche Nachricht --------
Von: Sven Neuhaus notifications@github.com 
Datum: 01.12.2015  09:04  (GMT+01:00) 
An: heavykick/MilkVRLauncher MilkVRLauncher@noreply.github.com 
Betreff: [MilkVRLauncher] Build instructions (#1) 

Thanks for writing this useful tool!

Could you whip up a minimal README that explains how to build this thing?

After building,  I need to sign the binary with my osig file from Oculus, right?

**Comment by neuhaus** [comment]
OK, never mind then.
