### ISSUE TITLE
MilkVRLauncher opening ALL my links

### ISSUE THREAD

**Issue by ghost** [heavykick/MilkVRLauncher#3]
Hi, app is awesome, so first let me thank you! However the issue I have now is that it works too well as it opens every link I click (for example videos on my synology NAS) with MilkVRLauncher. I cant launch any videos with my regular apps. Any idea how I could select what app to open a video with?

**Comment by heavykick** [comment]
Hi :)

I recommend the app "Better open with" ... I have it as default for the most intents, because of the fact that samsung did decide that once you have chosen a app to open something this app should be alwas the default app ..  big fail by samsung :(

**Comment by ghost** [comment]
Thanks man, this solved my issue in a heartbeat! Gotta love this community!
I discovered VR for the first time yesterday and already obsessed with it.

Best regards
