### ISSUE TITLE
Any plans to update to samsungvrmobile://

### ISSUE THREAD

**Issue by JohnRSim** [heavykick/MilkVRLauncher#5]
samsungvrmobile://sideload/?url=file:///storage/emulated/0/MyVideos/CarBee.mp4&video_type=_mono360&audio_type=_5.1&title=videotitle

With the rebrand of milkvr will you update the app to support the above :)

Thanks

**Comment by heavykick** [comment]
Ohh ... ok, i am not shure because the old intent is still working and a new version of MilkVRLauncher would than not longer work with old milkVR.
But you are right, I change that as soo as possible ...

**Comment by heavykick** [comment]
I got confirmed from DrewVR that there is no problem with the intent and the downwoard compatible is keept.
