### ISSUE TITLE
Player seeker?

### ISSUE THREAD

**Issue by stupherz** [heavykick/MilkVRLauncher#6]
Don't know if its just me but the time for the video is always 0.00. Not sure if there is a work around or if this was intended?

Thanks for your hard work.

**Comment by heavykick** [comment]
Hi :)

I did see this before when the media player is transcoding the Video. In
this case the Videos are not seekable....

Which media player do you use?

Am 27.11.2016 9:14 vorm. schrieb "stupherz" <notifications@github.com>:
>
> Don't know if its just me but the time for the video is always 0.00. Not
sure if there is a work around or if this was intended?

**Comment by stupherz** [comment]
Hi. I dug through some more old threads from like 11 months ago and I found that using Bubble or anDLNA through the Emby server fixes the seeker issue. But now another issue has popped up in that the resolution is defaulting to _3DH. It was fine for 3 videos, and now I've spent a couple hours trying to figure out why its defaulting to _3DH. Any suggestions? I tried Emby, bubble, anDLNA player and it always defaults to _3DH. This is a problem because for some reason changing the resolution settings in milkVRlauncher isnt doing anything. It just glitches and sticks to _3DH.

**Comment by heavykick** [comment]
The mikVR launcher does do a analyze of the url, and if "_3dh" is part of
the url it will preset 3dh automatically. But you can still set any othere
Format manually ...

Am 27.11.2016 11:00 vorm. schrieb "stupherz" <notifications@github.com>:
