### ISSUE TITLE
Default the name to filename?

### ISSUE THREAD

**Issue by fma965** [heavykick/MilkVRLauncher#7]
Is this possible? so instead of milkvrvideo or whatever by default its the filename. windows is my area not android.

**Comment by heavykick** [comment]
Hi :)
if the filename part of the url it should not be that hard ... but i am also a windows dev, a web dev could make us easy a regex that would give me the filename ... :(

**Comment by heavykick** [comment]
ahh .. nice ... found it at google:
Uri uri = new Uri(hreflink);
if (uri.IsFile) {
    string filename = System.IO.Path.GetFileName(uri.LocalPath);
}

will try it tomorrow ...

**Comment by heavykick** [comment]
ok .. done .. :)
Check Version 1.5

**Comment by fma965** [comment]
Awesome. :) Thanks

**Comment by heavykick** [comment]
no problem ... i am always thankfull for new ideas :)
